[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = cmsis

; --- SERIAL UPLOAD SETTINGS ---
upload_protocol = serial
upload_port = COM9
upload_speed = 115200

; --- SERIAL MONITOR SETTINGS ---
monitor_speed = 9600
monitor_filters = 
    direct
    send_on_enter
    

build_flags = -D STM32F103xB